import "./globals.css";
import type { Metadata } from "next";
import { Hind } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";

//Components:
import Navbar from "./components/navbar";

//Default Font:
const hind = Hind({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Pomotodo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${hind.className}`}>
        <div className="container p-4 mx-auto">
          <Navbar />
          {children}
          <Analytics />
        </div>
      </body>
    </html>
  );
}
